### ISSUE TITLE
Inaccurate seeking with some videos with "large" timestamps

### ISSUE THREAD

**Issue by Yves33** [RomanArzumanyan/VALI#108]
**Describe the bug**
Seeking by timestamp or by frame number is (very) inaccurate. 
+ issue appears both with real or test videos (h264 at least)
+ issue does not appear with deprecated VPF
+ seeking seems accurate for small offsets (less than 9s)

**System info**
1. OS : GNU/Linux fedora 39
2. GPU : NVIDIA GeForce RTX 3060
3. Driver and CUDA version Driver Version: 560.35.03      CUDA Version: 12.6
4. VALI.__version__=4.1.3-0

**To Reproduce**
1) generate test video with timestamps (30fps)
`ffmpeg -f lavfi -i testsrc=duration=300:size=640x480:rate=30 -filter_complex "drawtext=fontsize=96: text='%{pts \:flt}': x=100 : y=50 : box=1" -profile:v baseline -pix_fmt yuv420p -y ../tests/data/output.mp4`
2) open notebook test_seek.ipynb and adjust path of test video
`url="../tests/data/output.mp4"`
3) add a cell (below last cell) and enter the following code (uncomment/comment to test appropriate case)
```
#decode_show_video_frame(6.45) ## works: ->seeks to 6.46667 s
decode_show_video_frame(9.2)  ## fails: ->seeks to 17.53333 s
#decode_show_video(151)        ## works: ->seeks to to 5.0333 (expected ts=151/30=5.0333)
#decode_show_video_frame(301)  ## fails: ->seeks to 18.36 s   (expected ts=301/30=10.033)

```
**Expected behavior**
equivalent code by pyAV or vpf yields correct frames

**Comment by Yves33** [comment]
Additional info:
+ In TaskDecodeFrame.cpp (870 and below)
It seems that we're starting decoding from start of file (the farther we seek, the higher the number of decoded images)
+ The issue appears although if we forge GOP size (-g 120 -keyint_min 120), although the seektimes may be different

**Comment by RomanArzumanyan** [comment]
Hi @Yves33 

I do confirm the issue reproduction on my side, will come back as I find something.

**Comment by RomanArzumanyan** [comment]
Hi @Yves33 

Please check out `issue_108` branch.

On my machine it fixes the seek issue. Please note that `PyDecoder` when used with Nvdec acceleration may provide decoded frame pts values which are ever so slightly off in comparison to packet pts values.

It happens because of supposed, (I didn't see acknowledge from Video Codec SDK) bug, when cuvid sometimes produce non-monotonous pts values increase. So I have to rely on libavcodec to reconstruct pts timestamps.

Unit test compares timestamps with 1% precision. Please LMK if it fixes your issue.

P. S.
I was't able to overcome the "seek to frame 0" issue. It persists and it hurts performance. But it shall not affect seek accuracy.

**Comment by Yves33** [comment]
I guess we cannot consider the issue as being solved:
with branch issue_108, on my machine:
+ VALI now seeks to ~correct timestamps
But
+ VALI still decodes **all** frames from 0 to requested frame, which makes seeking extremely slow compared to pyAV and (deprecated) VPF, or any player (vlc, mpv, ...).  
Using above example (ouput.mp4), seeking to ts=259.5 s decodes 7787 frames (7787/30=259.56..) and takes ~2s on my machine (even longer with higher resolution movies)

**Comment by Yves33** [comment]
maybe some solutions  to explore?
+ https://stackoverflow.com/questions/64659237/problem-av-seek-frame-always-returns-me-the-beginning-of-the-video
tried to implement,  (although my C++ / libav* are very limited) but did'nt solve

+https://ffmpeg.org/pipermail/libav-user/2011-September/000624.html
calling avcodec_flush_buffers(); before / after av_seek_frame()

**Comment by RomanArzumanyan** [comment]
Thanks for the update @Yves33 

I'll take a closer look tomorrow, although I'm a bit skeptical - all these flushes and repetitive calls looks like some dark magic.
IMO if `avformat_seek_file` returns success but doesn't actually seek within given bounds it looks like a ffmpeg bug to me.

**Comment by Yves33** [comment]
Some more readings regarding avcodec_flush_buffers():  
+https://stackoverflow.com/questions/6395100/problem-with-ffmpeg-function-avformat-seek-file  
+http://dranger.com/ffmpeg/tutorial07.html  
+https://stackoverflow.com/questions/504792/ffmpeg-av-seek-frame  
+https://stackoverflow.com/questions/5261658/how-to-seek-in-ffmpeg-c-c  
pyAV also performs some kind of buffer flush after container.seek (https://github.com/PyAV-Org/PyAV/blob/170577208a5f73ef2ee5987b697ff9776b71e4a3/av/container/input.pyx#L268)

I've tried to call avcodec_flush_buffers(m_avc_ctx.get()), but no success so far (but my understanding of libav* and cuvid APIs is close to 0).

regarding possible bugs in ffmpeg, one may not exclude it, but given the number of softwares that use ffmpeg libs and that seek properly, I doubt such a severe bug would remain in the libs ! (plus pyAV, VPF, ffplay (...) can seek quite fast

**Comment by RomanArzumanyan** [comment]
I assume it would be better to merge `issue_108` to `main` for now and go on with your PR.
Although, seek performance is very important topic, so a bit later I'll move this thread to discussions and will continue the research on this matter.

> I doubt such a severe bug would remain in the libs

VPF didn't rely on libavcodec for actual decoding on GPU. It was only used to read packets and extract elementary bitstream. So `PyNvDecoder` was quite flexible class. Although it had tons of small-ish issues which were draining human-hours like hell.

**Comment by Yves33** [comment]
ok for merging, as issue_108 branch solves the problem, at the cost of weird performance.
