### ISSUE TITLE
Found relative path while evaluating include directories of "_PyNvCodec":

### ISSUE THREAD

**Issue by skier233** [RomanArzumanyan/VALI#38]
I've followed the windows installation steps exactly but I'm running into issues when trying to build VALI on windows:

```
      CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
      Please set them or make sure they are set and tested correctly in the CMake files:
      AVCODEC_INCLUDE_DIRS
         used as include directory in directory C:/Coding/Testing/PyTorch/MultiLabelClassification_Patreon/testing_copy/VALI/src/PyNvCodec
         used as include directory in directory C:/Coding/Testing/PyTorch/MultiLabelClassification_Patreon/testing_copy/VALI/src/PyNvCodec
         used as include directory in directory C:/Coding/Testing/PyTorch/MultiLabelClassification_Patreon/testing_copy/VALI/src/TC
         used as include directory in directory C:/Coding/Testing/PyTorch/MultiLabelClassification_Patreon/testing_copy/VALI/src/TC
      AVCODEC_LIBRARIES
          linked by target "_PyNvCodec" in directory C:/Coding/Testing/PyTorch/MultiLabelClassification_Patreon/testing_copy/VALI/src/PyNvCodec
          linked by target "TC" in directory C:/Coding/Testing/PyTorch/MultiLabelClassification_Patreon/testing_copy/VALI/src/TC
      AVFORMAT_INCLUDE_DIRS
         used as include directory in directory C:/Coding/Testing/PyTorch/MultiLabelClassification_Patreon/testing_copy/VALI/src/PyNvCodec
         used as include directory in directory C:/Coding/Testing/PyTorch/MultiLabelClassification_Patreon/testing_copy/VALI/src/PyNvCodec
         used as include directory in directory C:/Coding/Testing/PyTorch/MultiLabelClassification_Patreon/testing_copy/VALI/src/TC
         used as include directory in directory C:/Coding/Testing/PyTorch/MultiLabelClassification_Patreon/testing_copy/VALI/src/TC
      AVFORMAT_LIBRARIES
          linked by target "_PyNvCodec" in directory C:/Coding/Testing/PyTorch/MultiLabelClassification_Patreon/testing_copy/VALI/src/PyNvCodec
          linked by target "TC" in directory C:/Coding/Testing/PyTorch/MultiLabelClassification_Patreon/testing_copy/VALI/src/TC
      AVUTIL_INCLUDE_DIRS
         used as include directory in directory C:/Coding/Testing/PyTorch/MultiLabelClassification_Patreon/testing_copy/VALI/src/PyNvCodec
         used as include directory in directory C:/Coding/Testing/PyTorch/MultiLabelClassification_Patreon/testing_copy/VALI/src/PyNvCodec
         used as include directory in directory C:/Coding/Testing/PyTorch/MultiLabelClassification_Patreon/testing_copy/VALI/src/TC
         used as include directory in directory C:/Coding/Testing/PyTorch/MultiLabelClassification_Patreon/testing_copy/VALI/src/TC
      AVUTIL_LIBRARIES
          linked by target "_PyNvCodec" in directory C:/Coding/Testing/PyTorch/MultiLabelClassification_Patreon/testing_copy/VALI/src/PyNvCodec
          linked by target "TC" in directory C:/Coding/Testing/PyTorch/MultiLabelClassification_Patreon/testing_copy/VALI/src/TC
      SWRESAMPLE_INCLUDE_DIRS
         used as include directory in directory C:/Coding/Testing/PyTorch/MultiLabelClassification_Patreon/testing_copy/VALI/src/PyNvCodec
         used as include directory in directory C:/Coding/Testing/PyTorch/MultiLabelClassification_Patreon/testing_copy/VALI/src/PyNvCodec
         used as include directory in directory C:/Coding/Testing/PyTorch/MultiLabelClassification_Patreon/testing_copy/VALI/src/TC
         used as include directory in directory C:/Coding/Testing/PyTorch/MultiLabelClassification_Patreon/testing_copy/VALI/src/TC
      SWRESAMPLE_LIBRARIES
          linked by target "_PyNvCodec" in directory C:/Coding/Testing/PyTorch/MultiLabelClassification_Patreon/testing_copy/VALI/src/PyNvCodec
          linked by target "TC" in directory C:/Coding/Testing/PyTorch/MultiLabelClassification_Patreon/testing_copy/VALI/src/TC
      SWSCALE_INCLUDE_DIRS
         used as include directory in directory C:/Coding/Testing/PyTorch/MultiLabelClassification_Patreon/testing_copy/VALI/src/PyNvCodec
         used as include directory in directory C:/Coding/Testing/PyTorch/MultiLabelClassification_Patreon/testing_copy/VALI/src/PyNvCodec
         used as include directory in directory C:/Coding/Testing/PyTorch/MultiLabelClassification_Patreon/testing_copy/VALI/src/TC
         used as include directory in directory C:/Coding/Testing/PyTorch/MultiLabelClassification_Patreon/testing_copy/VALI/src/TC
      SWSCALE_LIBRARIES
          linked by target "_PyNvCodec" in directory C:/Coding/Testing/PyTorch/MultiLabelClassification_Patreon/testing_copy/VALI/src/PyNvCodec
          linked by target "TC" in directory C:/Coding/Testing/PyTorch/MultiLabelClassification_Patreon/testing_copy/VALI/src/TC

      CMake Error in src/PyNvCodec/CMakeLists.txt:
        Found relative path while evaluating include directories of "_PyNvCodec":

          "AVFORMAT_INCLUDE_DIRS-NOTFOUND"



      CMake Error in src/PyNvCodec/CMakeLists.txt:
        Found relative path while evaluating include directories of "_PyNvCodec":

          "AVFORMAT_INCLUDE_DIRS-NOTFOUND"
```

**Comment by RomanArzumanyan** [comment]
Hi @skier233 

From what I see in your log, CMake cant find FFMpeg library.
You need to download FFMpeg Windows build and provide CMake with the path to its location.
Here's a CLI example of how its done in VALI CI:
https://github.com/RomanArzumanyan/VALI/blob/03079c5d1ba4baf6903a08b5be7f80eceb66f7aa/.github/workflows/onPullRequest.yml#L90-L104

You don't need to set up Python venv, but the rest shall be relevant. Please make sure you follow this approach and LMK if you have any issues with that.

**Comment by skier233** [comment]
> Hi @skier233
> 
> From what I see in your log, CMake cant find FFMpeg library. You need to download FFMpeg Windows build and provide CMake with the path to its location. Here's a CLI example of how its done in VALI CI:
> 
> https://github.com/RomanArzumanyan/VALI/blob/03079c5d1ba4baf6903a08b5be7f80eceb66f7aa/.github/workflows/onPullRequest.yml#L90-L104
> 
> You don't need to set up Python venv, but the rest shall be relevant. Please make sure you follow this approach and LMK if you have any issues with that.

I install ffmpeg with conda install conda-forge ffmpeg=6.1. I verify that the installation works and that nvdec and nvenc are in the list of encoders (also nvdec works using torchaudio). 

I then set that path to: `$env:SKBUILD_CONFIGURE_OPTIONS="-DFFMPEG_ROOT=C:\Users\tyler\anaconda3\envs\ai_model_server_experiment\Library\bin"`
I see the ffmpeg.exe in that folder if I check manually

**Comment by RomanArzumanyan** [comment]
Hi @skier233 

> C:\Users\tyler\anaconda3\envs\ai_model_server_experiment\Library\bin

Please make sure that `FFMPEG_ROOT` points to the directory which has both FFMpeg libraries and headers.

**Comment by skier233** [comment]
If I install ffmpeg like this and set the path to the ffmpeg folder (which is exactly as it was downloaded so should have the headers and binary), I also get the same error:
```

# Define the download URL for the BtbN prebuilt FFmpeg with development files
$ffmpegUrl = "https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n6.1-latest-win64-gpl-shared-6.1.zip"

# Download FFmpeg
Invoke-WebRequest -Uri $ffmpegUrl -OutFile ffmpeg.zip

# Extract the zip file using built-in tools
Expand-Archive -Path ffmpeg.zip -DestinationPath .\ffmpeg

# Define the source directory (it should be the only directory in the extracted folder)
$ffmpegSourceDir = Get-ChildItem -Directory .\ffmpeg | Select-Object -ExpandProperty FullName

# Define the destination directory
$ffmpegDestDir = "$env:CONDA_PREFIX\Library\ffmpeg"

# Ensure the destination directory exists and is empty
if (Test-Path -Path $ffmpegDestDir) {
    Remove-Item -Recurse -Force -Path $ffmpegDestDir
}
New-Item -ItemType Directory -Path $ffmpegDestDir

# Move the entire FFmpeg folder to the conda environment
Copy-Item -Path "$ffmpegSourceDir\*" -Destination $ffmpegDestDir -Recurse -Force

# Update the PATH environment variable to include the FFmpeg binaries in the conda environment
$env:PATH = "$ffmpegDestDir\bin;$env:PATH"

# Clean up the downloaded zip and extracted files
Remove-Item -Recurse -Force .\ffmpeg
Remove-Item -Force ffmpeg.zip

# Verify installation using the full path
$ffmpegPath = "$ffmpegDestDir\bin\ffmpeg.exe"
& $ffmpegPath -hwaccels

# Confirm the correct ffmpeg is being used
Get-Command ffmpeg

# Check hardware acceleration support again
ffmpeg -hwaccels

```
ffmpeg version n6.1.1-100-g2aad37688c-20240520

`$env:SKBUILD_CONFIGURE_OPTIONS="-DFFMPEG_ROOT=C:\Users\tyler\anaconda3\envs\ai_model_server_experiment\Library\ffmpeg"`

Here is what the contents of that folder look like:
![image](https://github.com/RomanArzumanyan/VALI/assets/39396856/34a62b38-6ec2-4e08-8a4d-2b37fb9aba6c)

Headers are in the include folder, binaries in the bin folder

This gets the same error.

**Comment by RomanArzumanyan** [comment]
@skier233 

Please don't forget to delete build cache. Usually it's located in `_skbuild` folder.

**Comment by skier233** [comment]
> @skier233
> 
> Please don't forget to delete build cache after you've changed your build settings. Usually it's located `_skbuild` folder.

I just deleted the folder inside that folder and tried again and it gets the same error.

**Comment by skier233** [comment]
> Ok, what's your Python version?

Python 3.11.9

**Comment by RomanArzumanyan** [comment]
Any chance you can test vanilla python from https://www.python.org/downloads/windows/? I don't have an access to Anaconda distros, can't repro on my side.

**Comment by skier233** [comment]
> Any chance you can test vanilla python from https://www.python.org/downloads/windows/? I don't have an access to Anaconda distros, can't repro on my side.

Will test it

**Comment by skier233** [comment]
> Any chance you can test vanilla python from https://www.python.org/downloads/windows/? I don't have an access to Anaconda distros, can't repro on my side.

Tested with the vanilla python 3.11.0 on my host os and its the same error.

**Comment by RomanArzumanyan** [comment]
Path to FFMpeg is crippled. Here's how it looks in log file:
```
-DFFMPEG_ROOT=C:Userstyleranaconda3envsai_model_server_experimentLibraryffmpeg
```

It happens because you use backward slashes:
```
$env:SKBUILD_CONFIGURE_OPTIONS="-DFFMPEG_ROOT=C:\Users\tyler\anaconda3\envs\ai_model_server_experiment\Library\ffmpeg
```

Please use forward slashes instead:
```
set SKBUILD_CONFIGURE_OPTIONS="-DFFMPEG_ROOT=D:/install/ffmpeg-master-latest-win64-gpl-shared"
```

**Comment by skier233** [comment]
> Path to FFMpeg is crippled. Here's how it looks in your log file:
> 
> ```
> -DFFMPEG_ROOT=C:Userstyleranaconda3envsai_model_server_experimentLibraryffmpeg
> ```
> 
> It happens because you use backward slashes:
> 
> ```
> $env:SKBUILD_CONFIGURE_OPTIONS="-DFFMPEG_ROOT=C:\Users\tyler\anaconda3\envs\ai_model_server_experiment\Library\ffmpeg
> ```
> 
> Please use forward slashes instead:
> 
> ```
> set SKBUILD_CONFIGURE_OPTIONS="-DFFMPEG_ROOT=D:/install/ffmpeg-master-latest-win64-gpl-shared"
> ```

That did it. The install succeeds now. What a classic mistake. Thanks for the help debugging this!

**Comment by RomanArzumanyan** [comment]
> I see it mentioned in the README still

It's my mistake, I forgot to cleanup the readme.
`PytorchNvCodec` is dead, because VALI now supports`DLPack` specification and can share the memory with torch.


> is there any documentation on the new recommended flow with Pytorch?

You can follow torch segmentation unit test:
https://github.com/RomanArzumanyan/VALI/blob/03079c5d1ba4baf6903a08b5be7f80eceb66f7aa/tests/test_TorchSegmentation.py#L226-L231

Basically all VALI unit tests are written with lots of comments, one can follow them as samples.

Also there's an API documentation, you can find the link on the repo main page.

**Comment by skier233** [comment]
> > I see it mentioned in the README still
> 
> It's my mistake, I forgot to cleanup the readme. `PytorchNvCodec` is dead because VALI now supports`DLPack` specification and can share the memory with torch.
> 
> > is there any documentation on the new recommended flow with Pytorch?
> 
> You can follow torch segmentation unit test:
> 
> https://github.com/RomanArzumanyan/VALI/blob/03079c5d1ba4baf6903a08b5be7f80eceb66f7aa/tests/test_TorchSegmentation.py#L226-L231
> 
> Basically all VALI unit tests are written with lots of comments, one can follow them as samples.
> 
> Also there's an API documentation, you can find the link on the repo main page.

That's awesome that they now share the memory. I'll look around in there. Thanks for the help!
