### ISSUE TITLE
Surface.Make with YUV444

### ISSUE THREAD

**Issue by smivv** [RomanArzumanyan/VALI#48]
Hi,

Thanks for such an amazing product!
I'd like to contribute a bit to it by declaring a small bug (I suppose).
The format of the Surface YUV444 gets replaced with YUV422 so I am unable to run `nvc.PySurfaceConverter` to convert it.

Steps to introduce:
```
import PyNvCodec as nvc

nvc.Surface.Make(format=nvc.PixelFormat.YUV444, width=100, height=100, gpu_id=0)
```

The output:
```
Width:            100
Height:           100
Format:           YUV422
Pitch:            512
Elem size(bytes): 1
...
```

Let me know if you need more details, thanks!

**Comment by RomanArzumanyan** [comment]
Hi @smivv 
Thank you for the kind talk. 
Yep, that's a typo:
https://github.com/RomanArzumanyan/VALI/blob/84c542918f531adccb23c8fd5efa82c7e3613dd7/src/TC/inc/Surfaces.hpp#L218

Will fix it shortly.

**Comment by smivv** [comment]
One small request, if possible, could you please create a release with an updated patch version?

**Comment by RomanArzumanyan** [comment]
@smivv 
Sure, should have bumped patch version in the MR btw.
Please find v.3.1.1 in releases.
