### ISSUE TITLE
Bug? There's an unexpected behaviour when reading frames sequentially.

### ISSUE THREAD

**Issue by sotelo** [RomanArzumanyan/VALI#63]
Hello @RomanArzumanyan!

I might have found an issue with VALI, but there's also some chance that I'm just doing something totally wrong. When I read the attached video file with VALI, using the following code, I get a weird behaviour where the frames are read in an unexpected order (I get frame 0, 1, 0, 2). I'm attaching the output of the code below as well.

(Please note that the video starts until second 2... not sure if that's causing the issue).

```from PIL import Image
from IPython.display import display

import PyNvCodec as nvc
import numpy as np


url = "/data/jose/test-video-overdub/example_6/bug-video.mp4"

class StopExecution(Exception):
    def _render_traceback_(self):
        return []

# GPU-accelerated decoder
pyDec = nvc.PyDecoder(
    url,
    {},
    gpu_id=0)

# GPU-accelerated converter
pyCvt = nvc.PySurfaceConverter(
    pyDec.Format(),
    nvc.PixelFormat.RGB,
    gpu_id=0)

# Colorspace conversion context. Here a dummy set of parameters is used
# just for illustration purposes.
cc_ctx = nvc.ColorspaceConversionContext(
    nvc.ColorSpace.BT_709,
    nvc.ColorRange.MPEG)

# GPU-accelerated Surface downloader
pyDwn = nvc.PySurfaceDownloader(gpu_id=0)

# Raw decoded Surface
surf_src = nvc.Surface.Make(
    format=pyDec.Format(),
    width=pyDec.Width(),
    height=pyDec.Height(),
    gpu_id=0)

# Raw Surface, converted to RGB
surf_dst = nvc.Surface.Make(
    format=nvc.PixelFormat.RGB,
    width=pyDec.Width(),
    height=pyDec.Height(),
    gpu_id=0)

# Numpy array which contains decoded RGB Surface
frame = np.ndarray(
    dtype=np.uint8,
    shape=surf_dst.HostSize())


def save_image_from_tensor(f, path):
    image = Image.fromarray(f)
    image.save(path)


for idx in range(4):
    # Decode single Surface
    success, details = pyDec.DecodeSingleSurface(surf_src)
    if not success:
        print(details)
        raise StopExecution

    # Convert tot RGB
    success, details = pyCvt.Run(surf_src, surf_dst, cc_ctx)
    if not success:
        print(details)
        raise StopExecution

    # Copy pixels to numpy ndarray
    if not pyDwn.Run(surf_dst, frame):
        print("Failed to download surface")
        raise StopExecution

    # Reshape to proper dimensions.
    # Some video formats like NV12 require to reshape to 'raw' dimensions.
    # Others like RGB24 require to reshape to 'final' dimensions. Hence this
    # feature isn't yet supported by VALI out of the box. Have to do that by
    # hand. Sic !
    res_frame = np.reshape(
        frame,
        (pyDec.Height(), pyDec.Width(), 3))

    # Display in notebook

    image_f = Image.fromarray(res_frame)
    image_f.save(f"raw{idx}.png")
```

https://github.com/user-attachments/assets/047729de-5f2c-446a-a125-b6e5539c1f18

Output files:
---

![raw0](https://github.com/user-attachments/assets/67f4ae22-fb5e-4dad-81cc-4a4c119b6426)
![raw1](https://github.com/user-attachments/assets/57b79004-6ccb-4680-aa52-2868ac3a28fe)
![raw2](https://github.com/user-attachments/assets/2285bee6-fabc-43ef-b726-183f0b38bb0f)
![raw3](https://github.com/user-attachments/assets/4c8ddfa5-9674-4c7b-a222-1a59c1b964ad)

**Comment by RomanArzumanyan** [comment]
Hi @sotelo 

I’ll take a look tomorrow and will come back as I find something.

Meanwhile I recommend you to decode this video with ffmpeg using cuvid decoder and see if this behaviour reproduces.

**Comment by sotelo** [comment]
Thank you for the blazing fast response! I tried to decode it with VPF and it seems that that worked fine. Will also try with ffmpeg.

**Comment by Yves33** [comment]
Jus to mention that I have the same issue (out of order first frames with VALI but not with vpf). Did not explore much more

**Comment by RomanArzumanyan** [comment]
@Yves33 @sotelo 

Looks like I've found the culprit. Please check `v.3.2.6`.
After I changed CUDA stream used to memcpy ffmpeg frame to VALI to default CUDA stream, the issue no longer persists.
I've tested it locally on the video attached.
