### ISSUE TITLE
Get frame with all channel value is 0

### ISSUE THREAD

**Issue by evergreennha** [RomanArzumanyan/VALI#65]
I run file sample_decode_show.ipynb in sample dir, and get frame with all channel value is 0.
Please help me about this issue.

**Comment by evergreennha** [comment]
I checkout to branch v3.0.0, it work
please check with new version.

**Comment by RomanArzumanyan** [comment]
Hi @evergreennha 

Please check `v.3.2.6` and LMK if it persists. 
Maybe you're facing the same CUDA memcpy issue as #63 but it just reproduces differently on your machine.

**Comment by evergreennha** [comment]
Thank you so much for the fast response on this!
I will check it and response you soon.

**Comment by evergreennha** [comment]
I try branch v.3.2.6 but it still get that issue.
So I used cupy-cuda12x instead of PySurfaceDownloader and it work.
here is my code.
![Screenshot from 2024-07-24 15-36-23](https://github.com/user-attachments/assets/09e3e004-b26b-4b83-a0b9-27a1d13c6d1f)
I also fixed file PySurface.cpp to get  GpuMem
![Screenshot from 2024-07-24 15-43-05](https://github.com/user-attachments/assets/5aa4dbb9-414f-462a-9528-dacc868959bd)

**Comment by RomanArzumanyan** [comment]
@evergreennha 

There were lots of changes during last week and first half of this one.
Latest version is `v.3.2.10` which (this time for sure ! :) ) seem to have this issue fixed.
Please check it out and LMK if problem persists.

**Comment by evergreennha** [comment]
@RomanArzumanyan, sorry, that issue is still exists in v.3.2.10. :((
It's Having some problems with  class PySurfaceDownloader.
I'm also wondering if there's a problem with my installation. I am using Dockerfile in docker dir

**Comment by evergreennha** [comment]
Hi @RomanArzumanyan,
Here is my video https://drive.google.com/drive/u/0/folders/1vtxiQiViG4O54wyaGeIOsoMKQzAefirx

**Comment by evergreennha** [comment]
I realized that there is a difference between the size of surf_dst and frame
![Screenshot from 2024-07-25 10-38-15](https://github.com/user-attachments/assets/9f523e3e-a114-40c9-8526-7a682919902d)
Details value is "TaskExecInfo.SRC_DST_SIZE_MISMATCH"
![Screenshot from 2024-07-25 10-39-44](https://github.com/user-attachments/assets/4ed89fe1-62f2-42c0-8b66-c39bffadf265)
I also log size in file TaskCudaDownloadSurface.cpp on class
![Screenshot from 2024-07-25 10-42-27](https://github.com/user-attachments/assets/608f4574-6b69-4b70-acf6-deec7e6b64f0)
my log: size dst_buffer: 0 and size src_surface: 6220800

**Comment by evergreennha** [comment]
![Screenshot from 2024-07-25 10-52-19](https://github.com/user-attachments/assets/e9d304b5-f459-4cfb-9484-bafa1556843b)
I reset the condition to a value of 6220800 and it worked.
![Screenshot from 2024-07-25 11-10-56](https://github.com/user-attachments/assets/83a3bce8-c16d-4946-8eee-c1033e1eb5a6)
Here is my RGB frame
![b](https://github.com/user-attachments/assets/b939fa3d-f713-40a8-adf2-0b4abf9209a8)
 
please check "dst_buffer->GetRawMemSize()"

**Comment by RomanArzumanyan** [comment]
@evergreennha 

Sorry but I can't download the file from Google Disk.
Looks like some vendor lock because I can open the file in Firefox built-in player but cant' get the link and the download button doesn't work.
Can you upload it somewhere else ?

**Comment by RomanArzumanyan** [comment]
@evergreennha 

I works just fine on my machine
![Screenshot from 2024-07-25 17-53-01](https://github.com/user-attachments/assets/09abf46e-61e5-4024-be77-97d135c074e2)

**Comment by RomanArzumanyan** [comment]
@evergreennha 

> I realized that there is a difference between the size of surf_dst and frame

That's a good point. Can you print out the values if they are different ? That will help to find the culprit.

**Comment by evergreennha** [comment]
hi @RomanArzumanyan
All value get in function "dst_buffer->GetRawMemSize()" is 0. I  have tried in some different videos.
size dst_buffer: 0
![Screenshot from 2024-07-25 10-42-27](https://github.com/user-attachments/assets/0ffc4ead-dbe2-43d7-95c3-0edac4adba8d)

**Comment by evergreennha** [comment]
> strange

It's amazing machine!
I also wonder about pts value. Is it TimeStamp? .Pts in  PyNvCodec is Interger type, different from ffmpeg showinfo
Here is pts in ffpmeg:
Frame 0 - Timestamp: 0.08
Frame 1 - Timestamp: 0.12
Frame 2 - Timestamp: 0.16
Frame 3 - Timestamp: 0.2
Frame 4 - Timestamp: 0.24
Frame 5 - Timestamp: 0.28
Frame 6 - Timestamp: 0.32
Frame 7 - Timestamp: 0.36
Frame 8 - Timestamp: 0.44

**Comment by evergreennha** [comment]
> I run file sample_decode_show.ipynb in sample dir, and get frame with all channel value is 0. Please help me about this issue.

My issue is resolved by using another docker images (not nvidia/cuda:12.0.1-devel-ubuntu22.04).
Thank you for your helping.

**Comment by kadimon** [comment]
> My issue is resolved by using another docker images (not nvidia/cuda:12.0.1-devel-ubuntu22.04). Thank you for your helping.

Hi! I have the same problem. Which version are you using now?

**Comment by kadimon** [comment]
cuda 12.6,  driver 560.35.03, RTX3060 12GB, Arch

**Comment by evergreennha** [comment]
hello @kadimon 
I am using docker "nvcr.io/nvidia/tensorrt:24.04-py3" or another version have tensorrt.  Using cuda docker will get error, the reason can be not have cudnn or something.
