### ISSUE TITLE
Memory keeps rising when decoding rtsp stream

### ISSUE THREAD

**Issue by leyankon** [RomanArzumanyan/VALI#77]
**System info**
1. Ubuntu 22.04
2. GeForce RTX 3060
3. Driver Version: 535.183.01   CUDA Version: 11.8

**To Reproduce**
```
def update(source, gpuid, stream_index):
    try:
        # 尝试创建 PyFFmpegDemuxer 对象，处理视频流
        # , 'timeout': "10000000"
        pyDec = nvc.PyDecoder(source, {'timeout': "10000000", 'rtsp_transport': 'tcp'}, 0)
    except RuntimeError as e:
        logger.error(f"无法打开视频源 {source}: {e}")  # 记录错误日志
        return


    # 创建颜色空间转换器对象，将显存中的图像转换为BGR格式到内存中
    pyCvt = nvc.PySurfaceConverter(
        pyDec.Format(),
        nvc.PixelFormat.RGB,
        gpu_id=0)

    pyCvt2 = nvc.PySurfaceConverter(
        nvc.PixelFormat.RGB,
        nvc.PixelFormat.BGR,
        gpu_id=0)

    pyCvt3 = nvc.PySurfaceConverter(
        pyDec.Format(),
        nvc.PixelFormat.BGR,
        gpu_id=0
    )

    # 创建表面下载器对象，从GPU下载图像数据到内存
    pyDwn = nvc.PySurfaceDownloader(
        gpuid  # GPU编号
    )

    # 初始化变量
    rawFrame = np.ndarray((pyDec.Height(), pyDec.Width(), 3), dtype=np.uint8)  # 存储解码后的视频帧数据的数组
    # Raw decoded Surface
    surf_src = nvc.Surface.Make(
        format=pyDec.Format(),
        width=pyDec.Width(),
        height=pyDec.Height(),
        gpu_id=0)

    # Raw Surface, converted to RGB
    surf_dst = nvc.Surface.Make(
        format=nvc.PixelFormat.RGB,
        width=pyDec.Width(),
        height=pyDec.Height(),
        gpu_id=0)

    surf_dst2 = nvc.Surface.Make(
        format=nvc.PixelFormat.BGR,
        width=pyDec.Width(),
        height=pyDec.Height(),
        gpu_id=0)
    # Packet data
    pkt_data = nvc.PacketData()

    # 确定颜色空间转换参数
    cspace, crange = pyDec.ColorSpace(), pyDec.ColorRange()
    if nvc.ColorSpace.UNSPEC == cspace:
        cspace = nvc.ColorSpace.BT_709
    if nvc.ColorRange.UDEF == crange:
        crange = nvc.ColorRange.MPEG
    cc_ctx = nvc.ColorspaceConversionContext(cspace, crange)  # 创建颜色空间转换上下文对象

    # 获取视频帧率
    frame_rate = pyDec.AvgFramerate() if pyDec.AvgFramerate() is not None else 20

    while True:  # 循环处理视频流中的帧
        try:
            success, details = pyDec.DecodeSingleSurface(surf_src)
        except Exception as e:
            logger.error(f"处理视频帧时出现异常: {e}，{source}")  # 记录异常日志
            continue  # 继续下一次循环

update("rtsp://admin:13572468$@192.168.1.223:554/cam/realmonitor?channel=1&subtype=0", 0, 0)
```
```
success, details = pyDec.DecodeSingleSurface(surf_src) 
This code will cause RES to keep rising
```
My current VALI version is 3.2.10. I used PyFFmpegDemuxer 3.1.1 before, and RES will be fixed in a range.

**Comment by RomanArzumanyan** [comment]
Hi @leyankon 

> This code will cause RES to keep rising

What does that mean ?

From your code example I see that you decode video from RTSP source using tcp protocol and 10s timeout.
There are also multiple converters and downloader, none of them are used.

What's the exact problem ? vRAM consumption goes up over time ?

**Comment by leyankon** [comment]
@RomanArzumanyan 

```
success, details = pyDec.DecodeSingleSurface(surf_src) 
```
When this line of code exists, enter htop in the terminal, and you can see that the RES of the process continues to rise.

I'm wondering if this is normal?

**Comment by RomanArzumanyan** [comment]
Ok, so the actual question is "Non-swapped physical memory consumption goes up during RTSP stream decode".

That's very interesting and indeed important question which I have not investigated yet.
Why ? Because it's quite generic.

E. g. I can track memory allocations within VALI itself (`Surface`s and `Buffer`s and things of that kind) but I can't so easily do that for 3rd party libraries.

If you're willing to investigate on this possible issue that would be very helpful. Can you track memory consumption on some local video file ? If this behavior reproduces with one of the testing videos - that would be even better (easier to repro on my side).

**Comment by leyankon** [comment]
@RomanArzumanyan 
![1](https://github.com/user-attachments/assets/3f12e5f1-12dc-40c4-8156-46300f045947)
![2](https://github.com/user-attachments/assets/1321a9b1-9405-456e-a829-4aa16d980579)
I tested mp4 and had the same problem. I selected a one-hour video. From the beginning to the end, the RES increased by 1000M.
This should be a common situation.
Both video and rtsp will increase RES over time.

**Comment by RomanArzumanyan** [comment]
@leyankon 

Thanks for the update.
I'll repro on my side and will come back to you as I find somethig.

**Comment by RomanArzumanyan** [comment]
@leyankon 

It looks like I've found the memory leak reason: `av_packet_unref` call was missing within decoding loop.
Please check out latest `main` branch which has the patch and LMK if the issue persists. 
Otherwise if it's solved I'll draft a release.

P. S.
That's how I've checked memory consumption.
```python
import PyNvCodec as nvc

def getCurrentMemoryUsage():
    ''' Memory usage in kB '''

    with open('/proc/self/status') as f:
        memusage = f.read().split('VmRSS:')[1].split('\n')[0][:-3]

    return int(memusage.strip())

url = "tests/data/my/video.mp4"

pyDec = nvc.PyDecoder(url, {}, gpu_id=0)

surf_src = nvc.Surface.Make(
    format=pyDec.Format(),
    width=pyDec.Width(),
    height=pyDec.Height(),
    gpu_id=0)

while True:
    success, details = pyDec.DecodeSingleSurface(surf_src)
    if not success:
        print(details)
        break

    info = getCurrentMemoryUsage()
    print(info, flush=True)   
```

It outputs stable memory consumption through decoding loop:
```bash
321668
321668
321668
321668
...
321668
321668
321668
321668
...
321668
321668
321668
321668
TaskExecInfo.END_OF_STREAM
```

**Comment by leyankon** [comment]
@RomanArzumanyan 
Sorry for not getting back to you in time. I've tested it and now it's no problem. Thanks for the quick fix.

**Comment by kqv1** [comment]
Hello,

It seems that the memory problem is show up again.
I am using v4.2.0 in Windows

I have adapted @RomanArzumanyan test script for new version
```python
import python_vali as nvc
import psutil

def getCurrentMemoryUsage():
    ''' Memory usage in kB '''
    memusage = psutil.Process().memory_info().rss

    return int(memusage / 1024)

py_dec = nvc.PyDecoder("sample/video1.mp4", {}, gpu_id=0)

surf_src = nvc.Surface.Make(
    format=py_dec.Format,
    width=py_dec.Width,
    height=py_dec.Height,
    gpu_id=0)

while True:
    success, details = py_dec.DecodeSingleSurface(surf_src)
    if not success:
        print(details)
        break

    info = getCurrentMemoryUsage()
    print(info, flush=True) 
```
The output is increase
```
180316
180344
180408
180408
180408
180408
180408
...
184188
184188
184188
184188
TaskExecInfo.END_OF_STREAM
Press any key to continue . . .
```

Please take a look

**Comment by RomanArzumanyan** [comment]
Hi @kqv1 

Can you test on latest v.4.2.4 ?

**Comment by kqv1** [comment]
v4.2.4 still have the issue
```
178892
178920
178988
178988
...
182588
182588
182588
TaskExecInfo.END_OF_STREAM
```

**Comment by RomanArzumanyan** [comment]
@kqv1 

Apologies for the delayed reply.
I'll try to repro on my Windows laptop some time tomorrow and will come back as I find something.
