### ISSUE TITLE
How do I know, what resolutions does PyNvDecoder support?

### ISSUE THREAD

**Issue by XZG-0457** [RomanArzumanyan/VALI#85]
My business may be quite special, as many resolutions are not in standard formats, such as `5440 * 1440`, `1920 * 544`, `766 * 576`, etc.

When I tested the VPF, I found that PyNvDecoder did not seem to support the 1920 * 544 resolution rtsp stream I am currently using, that is, it would get stuck when running to this sentence, specifically:
```python
(py3_10) root@xx:/home/xx/# python3 SampleDecodeMultiThread.py 0 "rtsp://192.168.7.206/xx" 1
This sample decodes video streams in parallel threads. It does not save output.
GPU-accelerated color conversion and resize are also applied.
This sample may serve as a stability test.
Usage: python SampleDecodeMultiThread.py $gpu_id $input $num_threads
Create Decoder object..........




```

And if it is a 1920 * 1080 rtsp stream, there is no problem, specifically:
```python
(py3_10) root@xx:/home/xxx# python3 SampleDecodeMultiThread.py 0 "rtsp://192.168.7.206/xxx" 1
This sample decodes video streams in parallel threads. It does not save output.
GPU-accelerated color conversion and resize are also applied.
This sample may serve as a stability test.
Usage: python SampleDecodeMultiThread.py $gpu_id $input $num_threads
Create Decoder object..........
1920 1080 ............width and height
Color space:  ColorSpace.BT_601
Color range:  ColorRange.MPEG
[rtsp @ 0x27f70c0] jitter buffer full
[rtsp @ 0x27f70c0] RTP: missed 740 packets

```

code:

```python
    def __init__(self, gpuID, encFile):
        Thread.__init__(self)

        # Retain primary CUDA device context and create separate stream per thread.
        self.ctx = cuda.Device(gpuID).retain_primary_context()
        self.ctx.push()
        self.str = cuda.Stream()
        self.ctx.pop()
        self.encFile = encFile
        # Create Decoder with given CUDA context & stream.
        print("Create Decoder object..........")
        self.nvDec = nvc.PyNvDecoder(encFile, self.ctx.handle, self.str.handle)

        width, height = self.nvDec.Width(), self.nvDec.Height()
        print(width,height,"............width and height")
        hwidth, hheight = int(width / 2), int(height / 2)

```

Can this be solved?

**Comment by RomanArzumanyan** [comment]
Hi @XZG-0457 

Please check out latest VALI version. `PyNvDecoder` and `PyFfmpegDecoder` classes were both discontinued some time ago for the sake of one unified decoder class `PyDecoder` which supports both CPU and GPU through Video Codec SDK back-end to libavcodec library.

WRT to your original question:
> How do I know, what resolutions does PyNvDecoder support?

It depends on the GPU installed on your machine and it's about max resolution that HW supports. Usually it's something like 4K or 8K for new HW. 

I'm not aware of how to collect list of decoder capabilities though libavcodec API. Probably, `nvml` library from Nvidia is a way to go. I don't know for sure if there's an API function that will take input resolution and say if it's supported or not. Most probably, only max resolution is listed in decoder capabilities but I'm not 100% sure.

**Comment by XZG-0457** [comment]
> Hi @XZG-0457
> 
> Please check out latest VALI version. `PyNvDecoder` and `PyFfmpegDecoder` classes were both discontinued some time ago for the sake of one unified decoder class `PyDecoder` which supports both CPU and GPU through libavcodec Video Codec SDK back-end.
> 
> WRT to your original question:
> 
> > How do I know, what resolutions does PyNvDecoder support?
> 
> It depends on the GPU installed on your machine and it's about max resolution that HW supports. Usually it's something like 4K or 8K for new HW.
> 
> I'm not aware of how to collect list of decoder capabilities though libavcodec API. Probably, `nvml` library from Nvidia is a way to go. I don't know for sure if there's an API function that will take input resolution and say if it's supported or not. Most probably, only max resolution is listed in decoder capabilities but I don't know for sure because I've never tried that.

Oh, thank you very much for your reply. I will try VALI, but I found that it seems to conflict with the VPF environment. The details are as follows:

```python
      /usr/include/c++/11/bits/stl_vector.h:653:9: note: candidate: ‘template<class _InputIterator, class> std::vector<_Tp, _Alloc>::vector(_InputIterator, _InputIterator, const allocator_type&) [with _InputIterator = _InputIterator; <template-parameter-2-2> = <template-parameter-1-2>; _Tp = std::pair<VPF::Pixel_Format, AVPixelFormat>; _Alloc = std::allocator<std::pair<VPF::Pixel_Format, AVPixelFormat> >]’
        653 |         vector(_InputIterator __first, _InputIterator __last,
            |         ^~~~~~
      /usr/include/c++/11/bits/stl_vector.h:653:9: note:   template argument deduction/substitution failed:
      /home/zdiai/VALI/src/TC/src/Utils.cpp:155:42: note:   candidate expects 3 arguments, 1 provided
        155 |              {GRAY12, AV_PIX_FMT_GRAY10}});
            |                                          ^
      In file included from /usr/include/c++/11/vector:67,
                       from /home/zdiai/VALI/src/TC/inc/MemoryInterfaces.hpp:20,
                       from /home/zdiai/VALI/src/TC/inc/Utils.hpp:23,
                       from /home/zdiai/VALI/src/TC/src/Utils.cpp:1:
      /usr/include/c++/11/bits/stl_vector.h:625:7: note: candidate: ‘std::vector<_Tp, _Alloc>::vector(std::initializer_list<_Tp>, const allocator_type&) [with _Tp = std::pair<VPF::Pixel_Format, AVPixelFormat>; _Alloc = std::allocator<std::pair<VPF::Pixel_Format, AVPixelFormat> >; std::vector<_Tp, _Alloc>::allocator_type = std::allocator<std::pair<VPF::Pixel_Format, AVPixelFormat> >]’
        625 |       vector(initializer_list<value_type> __l,
            |       ^~~~~~
      /usr/include/c++/11/bits/stl_vector.h:625:43: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘std::initializer_list<std::pair<VPF::Pixel_Format, AVPixelFormat> >’
        625 |       vector(initializer_list<value_type> __l,
            |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
      /usr/include/c++/11/bits/stl_vector.h:607:7: note: candidate: ‘std::vector<_Tp, _Alloc>::vector(std::vector<_Tp, _Alloc>&&, const allocator_type&) [with _Tp = std::pair<VPF::Pixel_Format, AVPixelFormat>; _Alloc = std::allocator<std::pair<VPF::Pixel_Format, AVPixelFormat> >; std::vector<_Tp, _Alloc>::allocator_type = std::allocator<std::pair<VPF::Pixel_Format, AVPixelFormat> >]’
        607 |       vector(vector&& __rv, const allocator_type& __m)

```

I think I will try to install the environment on another server today, but I am wondering now, does VALI support `1920 * 544` and `766 * 576` as I said above? I have measured the resolution of 5440 and it exceeds the decoder upper limit `4096x4096`, but the input of the first two rtsp streams will cause the entire thread to get stuck, which I feel is very strange.

**Comment by XZG-0457** [comment]
I've got the experimental results on another server, this is my code:
```python
import PyNvCodec as nvc

nvDec=nvc.PyDecoder("rtsp://192.168.7.206/1920_1080",{}, 0)
width = nvDec.Width()
height = nvDec.Height()
print(width,height,"............neDec")
```

The problem now is that when I change the resolution of the stream to 1920 * 544, the current code will be stuck and cannot exit, unless I directly `kill pid` on the other side, just change the rtsp:
```python
nvDec=nvc.PyDecoder("rtsp://192.168.7.206/1920_544",{}, 0)
```

**Comment by XZG-0457** [comment]
Oh, it seems that I forgot to add the rtsp stream parameters. I retested with ffprobe, my problem, thanks, I will use the remaining time to explore VALI, it looks like a great idea

**Comment by XZG-0457** [comment]
I have a new question, that is, I want to test the performance of the current VPF and VALI and other indicators, but now I find that my current resolution of 1920 * 544 is not recognized in the VPF. I find that the problem lies in the resolution I am using. In DecodeMultiThread I create the decoder this way:

`        # Retain primary CUDA device context and create separate stream per thread.
        self.ctx = cuda.Device(gpuID).retain_primary_context()
        self.ctx.push()
        self.str = cuda.Stream()
        self.ctx.pop()
        self.encFile = encFile
        # Create Decoder with given CUDA context & stream.
        print("Create Decoder object..........")
        self.nvDec = nvc.PyNvDecoder(encFile, self.ctx.handle, self.str.handle)`

But I found that I cannot add {"rtsp_transport":"tcp"} parameters to the `nvc.PyNvDecoder(encFile, self.ctx.handle, self.str.handle)` code, but VALI can indeed, I think Asking why, because this caused my failure to decode non-standard format rtsp streams using VPF

**Comment by RomanArzumanyan** [comment]
Hi @XZG-0457 

There are many possible reasons.
One of them being an explicit connection timeout handling which was added to VALI and never back-ported to VPF.

VPF has reached its EOL so there’s no chance (and little sense TBH) to analyze and fix its bugs.

**Comment by XZG-0457** [comment]
> Hi @XZG-0457
> 
> There are many possible reasons. One of them being an explicit connection timeout handling which was added to VALI and never back-ported to VPF.
> 
> VPF has reached its EOL so there’s no chance (and little sense TBH) to analyze and fix its bugs.

thanks
