### ISSUE TITLE
seek context does not seek backward

### ISSUE THREAD

**Issue by geheiligt** [RomanArzumanyan/VALI#89]
Hi,
previously this code used to work for any randomly ordered frame number inside the video:
```
seek_ctx = nvc.SeekContext(frame, nvc.SeekMode.PREV_KEY_FRAME))
nvDec.DecodeSingleSurface(surf_src, seek_ctx)
```

At least since 3.2.10 seek works fine as long as the frame number is increasing, but **if I want to seek back to a previous frame it is not possible and the highest so far requested frame is shown**.

**Comment by RomanArzumanyan** [comment]
Hi @geheiligt 

I'll do a local triage and will come back as I find something.

**Comment by RomanArzumanyan** [comment]
Hi @geheiligt 

Your issue is fixed in latest release.
